apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: docker-selenium
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: master
  url: https://www.selenium.dev/docker-selenium