apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: selenium-docker
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: standalone
      version: "4.16.1"  # Use the latest stable version
      sourceRef:
        kind: HelmRepository
        name: selenium
        namespace: flux-system
  values:
    # Selenium standalone configuration
    chrome:
      enabled: true
    firefox:
      enabled: true

    # Additional customizations
    serviceAccount:
      create: true

    # Resource allocations
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi
